
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tpnode3-pv
  labels:
    app: tpnode3-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client-254-111
  nfs:
    path: /mnt/disk/k8s_nfs_data/baas/tpxchain/tpnode3
    server: 192.168.254.111
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tpxchain
  name: tpnode3-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: tpnode3-pv