
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tpxchain
  name: tpnode3
spec:
  selector:
    matchLabels:
      app: tpxchain
      role: tpnode3
      org: tpnode3
      name: tpnode3
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: tpxchain
        role: tpnode3
        org: tpnode3
        name: tpnode3
    spec:
      containers:
      - name: tpnode3
        image: lonerii/xuperchain-nc:latest
        ports:
        - containerPort: 37101
        - containerPort: 47101
        volumeMounts:
        - mountPath: /home/work/xuperunion/data
          name: tpnode3data
          subPath: data/
        - mountPath: /home/work/xuperunion/conf
          name: tpnode3data
          subPath: conf/
        - mountPath: /home/work/xuperunion/logs
          name: tpnode3data
          subPath: logs/
      volumes:
      - name: tpnode3data
        persistentVolumeClaim:
          claimName: tpnode3-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: tpxchain
  name: tpnode3
spec:
  selector:
    app: tpxchain
    role: tpnode3
    org: tpnode3
    name: tpnode3
  type: NodePort
  ports:
  - name: rpc-endpoint
    protocol: TCP
    port: 37101
    targetPort: 37101
  - name: p2p-endpoint
    protocol: TCP
    port: 47101
    targetPort: 47101
